bin=cpus
cc=gcc
CFLAGS=-m32 -O2 -D_CPUID32_
ASFLAGS=-D_CPUID_LIN32_
.PHONY: clean all

.SUFFIXES:	.s
.s.o:
	$(cc) -c -x assembler-with-cpp $(CFLAGS) $(ASFLAGS) $<

all: $(bin)

$(bin): main.o cpuid.o excpuid.o
	$(cc) -m32 -o $(bin) main.o cpuid.o excpuid.o

main.o: main.c
	$(cc) -c $(CFLAGS) -D_CPUID_BUILTIN_VAR_ main.c
cpuid: cpuid.s
	$(cc)  cpuid.s
excpuid.o: excpuid.c
	$(cc) -c $(CFLAGS) excpuid.c

clean:
	 rm -f *.o $(bin) *~

